# This file was generated by GoReleaser. DO NOT EDIT.
cask "ruptor" do
  version "0.0.1-rc1"

  on_macos do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_x86_64.tar.gz"
      sha256 "41e8c307a3657c538d78947f272240038a622fbc577de32d8c38258dbfed597b"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_arm64.tar.gz"
      sha256 "4a05fa516d25970661b5ca3a43cf911beaba734d79a29107a3b7bbe97bc7c216"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_x86_64.tar.gz"
      sha256 "975c3beb45124fb742a5bccecba07c1bec7a98d879adfbaa5b0c2c2c9e166cd9"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_arm64.tar.gz"
      sha256 "20e0e3f68733218d0e7ac313fcfb62a2014a544e2db4075c327a591bf441e71d"
    end
  end

  name "ruptor"
  desc "Reliability testing CLI for AI agents"
  homepage "https://ruptor.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ruptor"

  # No zap stanza required

end
