# This file was generated by GoReleaser. DO NOT EDIT.
cask "ruptor" do
  version "0.0.1-rc1"

  on_macos do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_x86_64.tar.gz"
      sha256 "e58c346999ef2d3950c40787e541ca36d5aaf15349cfb5115a0df4f558dddf30"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_arm64.tar.gz"
      sha256 "3680a4c9b83f2a2ea43eb17aeec30c2fa07a7975f74a0bfaaaa6cb94845288d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_x86_64.tar.gz"
      sha256 "4c34849035bfe8cb819cd5fea51515c6ea5b417a39a428d085a39eaf5d302df6"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_arm64.tar.gz"
      sha256 "48ac78674a76c3554cf3d127cafaa7c92f3093e0fe8487800779643b66f9dd8f"
    end
  end

  name "ruptor"
  desc "Reliability testing CLI for AI agents"
  homepage "https://ruptor.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ruptor"

  # No zap stanza required

end
