# This file was generated by GoReleaser. DO NOT EDIT.
cask "ruptor" do
  version "0.0.1-rc1"

  on_macos do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_x86_64.tar.gz"
      sha256 "827f8231b74cb9eaa7857fa96bb6bcb5935ac881bd0470b0ebb64b69520f5300"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_macOS_arm64.tar.gz"
      sha256 "03d5f92e091e6947ba076a3c4ebec9b78e3c915f04120efd3dff0dcf95526152"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_x86_64.tar.gz"
      sha256 "2e45f2cc89d82602069347bcf85b41dde15774d205b74eb9e230a102a0ef1f58"
    end
    on_arm do
      url "https://github.com/ruptor-dev/cli/releases/download/v#{version}/ruptor_#{version}_Linux_arm64.tar.gz"
      sha256 "4256e5feaad28c9da83f83c1c7eab6241aa23fc67d7e05440ba21d18df1ac799"
    end
  end

  name "ruptor"
  desc "Reliability testing CLI for AI agents"
  homepage "https://ruptor.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ruptor"

  # No zap stanza required

end
